# Generated by Django 4.2.13 on 2024-05-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="visits",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
