# Generated by Django 4.2.13 on 2024-05-23 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='play',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
