# Generated by Django 4.2.13 on 2024-05-15 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Формат номера телефона должен быть +7-XXX-XXX-XX-XX",
                        regex="^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$",
                    )
                ],
            ),
        ),
    ]
